#!/usr/bin/env python3
"""Validate the candidate thesis map against the typed graph and render Markdown."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from jsonschema import Draft202012Validator

from public_safety import public_content_violations

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry" / "thesis-map.json"
SCHEMA = ROOT / "schemas" / "thesis-map.schema.json"
GRAPH = ROOT / "registry" / "evidence-graph.json"
CLAIMS = ROOT / "registry" / "claim-registry.json"
OUT = ROOT / "docs" / "THESIS_MAP.md"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def validate(payload: dict) -> list[str]:
    errors = [error.message for error in Draft202012Validator(load(SCHEMA)).iter_errors(payload)]
    graph = load(GRAPH)
    claims = {claim["claim_id"]: claim for claim in load(CLAIMS)["claims"]}
    graph_nodes = {node["node_id"]: node for node in graph["nodes"]}
    graph_edges = {(edge["source_node_id"], edge["edge_type"], edge["target_node_id"]): edge for edge in graph["edges"]}
    node_ids, path_ids, orders = [], [], []
    for thesis_node in payload.get("nodes", []):
        node_ids.append(thesis_node.get("stable_id")); orders.append(thesis_node.get("order"))
        for claim_id in thesis_node.get("claim_ids", []):
            if claim_id not in claims: errors.append(f"unknown thesis claim: {claim_id}")
        for field, expected_type in (("objections", "argument_object"), ("falsifiers", "argument_object"), ("proof_gaps", "proof_gap"), ("paper_sections", "paper_section")):
            for reference in thesis_node.get(field, []):
                if graph_nodes.get(reference, {}).get("node_type") != expected_type:
                    errors.append(f"unknown or mistyped thesis reference: {reference}")
        for path in thesis_node.get("evidence_paths", []):
            path_ids.append(path.get("path_id"))
            nodes, edge_types = path.get("node_ids", []), path.get("edge_types", [])
            if len(edge_types) != len(nodes) - 1:
                errors.append(f"evidence path length mismatch: {path.get('path_id')}")
                continue
            traversed = []
            for source, relation, target in zip(nodes[:-1], edge_types, nodes[1:], strict=True):
                edge = graph_edges.get((source, relation, target))
                if edge is None:
                    errors.append(f"evidence path edge absent: {path.get('path_id')} {source} {relation} {target}")
                else:
                    traversed.append(edge)
            if path.get("status") == "reproducible":
                if not any(graph_nodes.get(item, {}).get("node_type") == "chunk" for item in nodes):
                    errors.append(f"reproducible path lacks a stable chunk: {path.get('path_id')}")
                if any(edge.get("review_state") != "reviewed" for edge in traversed):
                    errors.append(f"reproducible path includes unreviewed edge: {path.get('path_id')}")
        if thesis_node.get("export_eligibility") == "eligible":
            ineligible = [claim_id for claim_id in thesis_node.get("claim_ids", []) if claims.get(claim_id, {}).get("publication_eligibility") != "eligible"]
            if ineligible: errors.append(f"eligible thesis node includes blocked claims: {thesis_node.get('stable_id')} {ineligible}")
            if thesis_node.get("review_state") != "reviewed": errors.append(f"eligible thesis node is not reviewed: {thesis_node.get('stable_id')}")
    if len(node_ids) != len(set(node_ids)): errors.append("thesis node IDs must be unique")
    if len(path_ids) != len(set(path_ids)): errors.append("thesis evidence path IDs must be unique")
    if orders != list(range(1, len(orders) + 1)): errors.append("thesis node order must be contiguous and canonical")
    for violation in public_content_violations(payload):
        errors.append(f"forbidden thesis-map content: {violation}")
    return errors


def markdown(payload: dict) -> bytes:
    claims = load(CLAIMS)["claims"]
    blocked_claim_count = sum(claim["publication_eligibility"] != "eligible" for claim in claims)
    lines = [
        "<!-- Generated by scripts/build_thesis_map.py; edit registry/thesis-map.json. -->",
        "# The Ajax Line — candidate thesis map",
        "",
        f"> **Blocked unpublished candidate.** This map is an argument-control surface, not a factual accusation or release authorization. {blocked_claim_count} of {len(claims)} claims remain blocked, quarantined, or retired.",
        "",
        payload["bounded_thesis"],
        "",
        "| # | Spine node | Status | Bounded proposition | Objection / falsifier | What it does not prove | Gate |",
        "|---:|---|---|---|---|---|---|",
    ]
    for item in payload["nodes"]:
        objections = ", ".join(item["objections"]) or "—"
        falsifiers = ", ".join(item["falsifiers"]) or "—"
        claims = ", ".join(item["claim_ids"])
        proposition = item["proposition"].replace("|", "\\|")
        does_not = item["does_not_prove"].replace("|", "\\|")
        lines.append(f"| {item['order']} | {item['stable_id']} · {item['role'].replace('_', ' ')}<br>{claims} | {item['epistemic_status']} | {proposition} | {objections}<br>Falsifier: {falsifiers} | {does_not} | {item['export_eligibility']} |")
    lines.extend([
        "",
        "## Evidence and release boundary",
        "",
        "- Exact reproducible path today: `SRC-0002 → chk:sha256:df2e…6227 → CLM-0002` for the bounded deployment-script observation only.",
        "- Every other path remains visibly candidate or unknown until its registered locator, review state, and claim gate pass.",
        "- Iliad/Trojan-War material is naming or possible epigraph material only; Move 37 is analogy and benchmark motivation, never causal evidence.",
        "- No public release is authorized. Human approval of the exact frozen export hash remains mandatory.",
        "",
    ])
    return "\n".join(lines).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = load(REGISTRY)
    errors = validate(payload)
    if errors:
        print("ERROR: thesis map invalid:\n" + "\n".join(errors), file=sys.stderr)
        return 1
    data = markdown(payload)
    if args.check:
        if not OUT.exists() or OUT.read_bytes() != data:
            print("ERROR: generated thesis map is stale; run scripts/build_thesis_map.py", file=sys.stderr)
            return 1
        print(f"thesis map current: {len(payload['nodes'])} candidate nodes; export blocked")
        return 0
    OUT.write_bytes(data)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(payload['nodes'])} candidate nodes; export blocked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
